### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by zhuoctian** [jerredchen/A1_SLAM#5]
Hello jerredchen! 
I'm using Unitree AlienGo but I think it's similar to A1,
so I want to try it on AlienGo.
How to use this package and What should I do on the robot side(for example launch the camera node)?
Thanks!

**Comment by jerredchen** [comment]
Hi! To be honest, I do not think that it will work on the AlienGo but you can try. To launch the main SLAM node, you can run `roslaunch a1_slam a1_slam.launch`. However, the camera node is separate and that will be dependent on the AlienGo (the camera node shown in the README was purely for visualization and not a part of the algorithm). Best of luck!
